name: Check Formatting
on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenSCAD
        run: |
          npm install -g openscad-format 
      - name: Check Formatting
        run: |
          ls *.scad util/*.scad |  xargs -I {} sh -c 'openscad-format --force --input {}'
          [[ ! `git status --porcelain` ]]